enum LoginState {
  UNKNOWN = 'UNKNOWN',
  LOGGED_OUT = 'LOGGED_OUT',
  LOGGED_IN = 'LOGGED_IN',
  PASSWORD_EXPIRED = 'PASSWORD_EXPIRED',
  UNAUTHENTICATED = 'UNAUTHENTICATED'
}

export default LoginState;
